config/routes.rb
Rails.application.routes.draw do
  resources :gardens do
    resources :plants, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/garden.rb
class Garden < ApplicationRecord
  has_many :plants, dependent: :destroy
  # @garden.plants -> returns an array of all Plant instances belonging to that garden
  validates :name, presence: true
  validates :banner_url, presence: true
end

app/models/plant.rb
class Plant < ApplicationRecord
  belongs_to :garden

  # @plant.garden -> this will return one instance of Garden
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gardens_controller.rb
class GardensController < ApplicationController
  before_action :set_garden, only: %i[ show edit update destroy ]

  # GET /gardens
  def index
    @gardens = Garden.all
  end

  # GET /gardens/1
  def show
    @plant = Plant.new
  end

  # GET /gardens/new
  def new
    @garden = Garden.new
  end

  # GET /gardens/1/edit
  def edit
  end

  # POST /gardens
  def create
    @garden = Garden.new(garden_params)

    if @garden.save
      redirect_to @garden, notice: "Garden was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /gardens/1
  def update
    if @garden.update(garden_params)
      redirect_to @garden, notice: "Garden was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /gardens/1
  def destroy
    @garden.destroy
    redirect_to gardens_url, notice: "Garden was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_garden
      @garden = Garden.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def garden_params
      params.require(:garden).permit(:name, :banner_url)
    end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  def create
    @plant = Plant.new(plant_params)
    @garden = Garden.find(params[:garden_id])
    @plant.garden = @garden
    if @plant.save
      redirect_to garden_path(@garden)
    else
      render 'gardens/show', status: :unprocessable_entity
    end
  end

  private

  def plant_params
    params.require(:plant).permit(:name, :image_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gardens_helper.rb
module GardensHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/views/gardens/_form.html.erb
<%= simple_form_for(@garden) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :banner_url %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/gardens/_garden.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), url(<%= garden.banner_url %>);">
  <div class="container">
    <h1><%= garden.name %></h1>
  </div>
</div>

app/views/gardens/edit.html.erb
<h1>Editing garden</h1>

<%= render "form", garden: @garden %>

<br>

<div>
  <%= link_to "Show this garden", @garden %> |
  <%= link_to "Back to gardens", gardens_path %>
</div>

app/views/gardens/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="container">
  <div class="d-flex justify-content-between align-items-center">
    <h1>Gardens</h1>
    <%= link_to "New garden", new_garden_path, class: 'btn btn-success' %>
  </div>

  <div id="gardens">
    <% @gardens.each do |garden| %>
      <%= link_to garden do %>
        <%= render garden %>
      <% end %>
      <br>
    <% end %>
  </div>
</div>

app/views/gardens/new.html.erb
<h1>New garden</h1>

<%= render "form", garden: @garden %>

<br>

<div>
  <%= link_to "Back to gardens", gardens_path %>
</div>

app/views/gardens/show.html.erb
<%= render @garden %>

<div class="container">
  <div class="row my-3">
    <div class="col-8">
      <h2 class="mb-3">My Plants</h2>
      <div class="cards">
        <% @garden.plants.each do |plant| %>
          <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.1)), url(<%= plant.image_url %>)">
            <%= plant.name %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-4">
      <h2 class="mb-3">Add a new plant</h2>
      <%= simple_form_for [@garden, @plant] do |f| %>
        <%= f.input :name %>
        <%= f.input :image_url %>
        <%= f.submit class: 'btn btn-success' %>
      <% end %>
    </div>
  </div>
  <%= link_to "Back to gardens", gardens_path, class: 'btn btn-outline-success btn-sm mt-3' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GardensAndPlants</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>